table CausalesIncompetencia
	lineageTag: acf7dd80-2ee5-4bd4-a66d-0e3d89dcfeec

	column id
		dataType: int64
		formatString: 0
		lineageTag: 6ad9b04c-0ff0-4d0e-9cbf-06d575569c27
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column 'Causales de incompetencia'
		dataType: string
		lineageTag: 5074a99e-a129-4d87-80ad-0950c6a5050a
		summarizeBy: none
		sourceColumn: Causales de incompetencia

		annotation SummarizationSetBy = Automatic

	partition CausalesIncompetencia = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\GabrielArmandoChávez\GONZALEZ CORTINA GLENDER Y CIA\ZAP BI - Documentos compartidos\02 OPORTUNIDADES\Oportunidades 2024\IPN\PoC\catalogos.xlsx"), null, true),
				    CausalesIncompetencia_Sheet = Origen{[Item="CausalesIncompetencia",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(CausalesIncompetencia_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id", Int64.Type}, {"Causales de incompetencia", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

