table DerechoProbablementeViolentado
	lineageTag: 2c8ca04d-3686-424c-b6c6-30b178c33dfd

	column id
		dataType: int64
		formatString: 0
		lineageTag: a5ba8abb-e632-48bd-b248-369f36523270
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column 'Derecho Probablemente Violentado'
		dataType: string
		lineageTag: b8d79c9e-0989-4242-b771-785334a644d5
		summarizeBy: none
		sourceColumn: Derecho Probablemente Violentado

		annotation SummarizationSetBy = Automatic

	partition DerechoProbablementeViolentado = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\GabrielArmandoChávez\GONZALEZ CORTINA GLENDER Y CIA\ZAP BI - Documentos compartidos\02 OPORTUNIDADES\Oportunidades 2024\IPN\PoC\catalogos.xlsx"), null, true),
				    DerechoProbablementeViolentado_Sheet = Origen{[Item="DerechoProbablementeViolentado",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(DerechoProbablementeViolentado_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id", Int64.Type}, {"Derecho Probablemente Violentado", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

