table EstatusActual
	lineageTag: d5ded5fb-4dcd-4d6d-9a21-e2a45b07bf8e

	column id
		dataType: int64
		formatString: 0
		lineageTag: 98505102-433b-44c2-8dbf-cdb13659bd35
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column 'Estatus actual'
		dataType: string
		lineageTag: 01553a1d-a3f2-40f6-b82b-5d3efdf5142d
		summarizeBy: none
		sourceColumn: Estatus actual

		annotation SummarizationSetBy = Automatic

	partition EstatusActual = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\GabrielArmandoChávez\GONZALEZ CORTINA GLENDER Y CIA\ZAP BI - Documentos compartidos\02 OPORTUNIDADES\Oportunidades 2024\IPN\PoC\catalogos.xlsx"), null, true),
				    EstatusActual_Sheet = Origen{[Item="EstatusActual",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(EstatusActual_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id", Int64.Type}, {"Estatus actual", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

