table Genero
	lineageTag: e530799f-ba63-4d78-8b8e-b60d6bb86f98

	column id
		dataType: int64
		formatString: 0
		lineageTag: ce9c98b7-08f8-4e9b-ae69-87de71eb7fbf
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column Genero
		dataType: string
		lineageTag: 11936380-a09e-4ba9-a567-2fe55d150b06
		summarizeBy: none
		sourceColumn: Genero

		annotation SummarizationSetBy = Automatic

	partition Genero = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\GabrielArmandoChávez\GONZALEZ CORTINA GLENDER Y CIA\ZAP BI - Documentos compartidos\02 OPORTUNIDADES\Oportunidades 2024\IPN\PoC\catalogos.xlsx"), null, true),
				    Genero_Sheet = Origen{[Item="Genero",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Genero_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id", Int64.Type}, {"Genero", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

