table 'Capacidad patios'
	lineageTag: 60ad252d-a55f-4f0e-a74d-33a896289da7

	measure 'Capacidad Disponible' = sum('Capacidad patios'[Capacidad])-count('BD Dwell Carros activos v1'[Fecha de posicionado])
		formatString: 0
		lineageTag: b4b17f65-4d71-432a-a654-c44c44e58954

	measure '% Disponible' = 'Capacidad patios'[Capacidad Disponible]/sum('Capacidad patios'[Capacidad])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a5f7167a-4e04-48fc-bb54-a9dc4569d83f

	column Patio
		dataType: string
		lineageTag: d2f05a6c-1d40-499d-b3d3-11a6d8dd298c
		summarizeBy: none
		sourceColumn: Patio

		annotation SummarizationSetBy = Automatic

	column Capacidad
		dataType: int64
		formatString: 0
		lineageTag: 8cef5fd9-688e-4413-880f-e889f59edef2
		summarizeBy: none
		sourceColumn: Capacidad

		annotation SummarizationSetBy = User

	column Lat
		dataType: double
		lineageTag: 73353bac-3099-4379-a904-52550a03f9a7
		dataCategory: Latitude
		summarizeBy: none
		sourceColumn: Lat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Lon
		dataType: double
		lineageTag: f2bd518d-d06d-42ea-be13-67f116b4d0ab
		dataCategory: Longitude
		summarizeBy: none
		sourceColumn: Lon

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Capacidad patios' = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:\Users\GabrielArmandoChávez\GONZALEZ CORTINA GLENDER Y CIA\ZAP BI - Documentos compartidos\02 OPORTUNIDADES\Oportunidades 2025\Ferrovalle\POV data\Capacidad patios.csv"),[Delimiter=","]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Lat", type number}, {"Lon", type number}}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Tipo cambiado1",{{"Patio", type text}, {"Capacidad", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

