table DimCategoriaDeCompras
	lineageTag: 31f70ade-38b3-4ef9-94bd-11ad23e459cd

	column IdCategoriaDeCompras
		dataType: int64
		formatString: 0
		lineageTag: d13633f2-41ae-4bfa-93a2-c4e42e97de10
		summarizeBy: none
		sourceColumn: IdCategoriaDeCompras

		annotation SummarizationSetBy = Automatic

	column Codigo
		dataType: string
		lineageTag: 1bf43888-ce1d-4be9-8966-295bc52a7d3f
		summarizeBy: none
		sourceColumn: Codigo

		annotation SummarizationSetBy = Automatic

	column Nombre
		dataType: string
		lineageTag: 82dc2c76-41d9-43b9-8857-7de0b16d83c3
		summarizeBy: none
		sourceColumn: Nombre

		annotation SummarizationSetBy = Automatic

	partition DimCategoriaDeCompras = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\GabrielArmandoChávez\OneDrive - GONZALEZ CORTINA GLENDER Y CIA\CategoriaDeCompras.xlsx"), null, true),
				    Hoja1_Sheet = Origen{[Item="Hoja1",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Hoja1_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"IdCategoriaDeCompras", Int64.Type}, {"Codigo", type text}, {"Nombre", type text}})
				in
				    #"Tipo cambiado"

	changedProperty = Name

	annotation PBI_ResultType = Table

