table Presupuesto
	lineageTag: e8516eb4-ce52-46bb-b2f4-2eac26680f6f

	column Año
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3cac0085-0caf-4a1f-b05c-d3669051e634
		summarizeBy: none
		sourceColumn: Año

		variation Variación
			isDefault
			relationship: aac2bd2e-ce3d-4672-bad4-3ee938e391f3
			defaultHierarchy: LocalDateTable_f10cfc63-3a6f-4219-8ce0-d5edadf1d5b3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Área
		dataType: string
		lineageTag: deea3294-781e-4659-a308-388259f30307
		summarizeBy: none
		sourceColumn: Área

		annotation SummarizationSetBy = Automatic

	column 'Presupuesto Asignado'
		dataType: int64
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: b8802e13-eb99-47b8-81af-c6d2c82922af
		summarizeBy: sum
		sourceColumn: Presupuesto Asignado

		annotation SummarizationSetBy = Automatic

	column 'Presupuesto Utilizado'
		dataType: int64
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: eb7ca3b1-f011-48bc-aea9-521bb451796b
		summarizeBy: sum
		sourceColumn: Presupuesto Utilizado

		annotation SummarizationSetBy = Automatic

	column Concepto
		dataType: string
		lineageTag: 881e3969-7590-4798-a0f9-015f9ea03944
		summarizeBy: none
		sourceColumn: Concepto

		annotation SummarizationSetBy = Automatic

	partition Presupuesto = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\DiegoDelaCabadaMoren\GONZALEZ CORTINA GLENDER Y CIA\ZAP BI - Documentos compartidos\02 OPORTUNIDADES\Oportunidades 2023\CONALEP\BD_Conalep_Alumnos_Servicio.xlsx"), null, true),
				    Presupuesto_Sheet = Origen{[Item="Presupuesto",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Presupuesto_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Año", type date}, {"Área", type text}, {"Presupuesto Asignado", Int64.Type}, {"Presupuesto Utilizado", Int64.Type}}),
				    #"Inicio del año calculado" = Table.TransformColumns(#"Tipo cambiado",{{"Año", Date.StartOfYear, type date}})
				in
				    #"Inicio del año calculado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

