CREATE TABLE [dbo].[custsettlment] (

	[TRANSRECID] bigint NULL, 
	[ACCOUNTNUM] bigint NULL, 
	[EXCHADJUSTMENT] float NULL, 
	[OFFSETTRANSVOUCHER] varchar(8000) NULL, 
	[SETTLEAMOUNTCUR] float NULL, 
	[SETTLEAMOUNTMST] float NULL, 
	[SETTLEMENTVOUCHER] varchar(8000) NULL, 
	[TRANSDATE] date NULL, 
	[CLOSEDDATE] date NULL, 
	[TRANSTYPE] bigint NULL, 
	[DATAAREAID] varchar(8000) NULL
);


GO
ALTER TABLE [dbo].[custsettlment] ADD CONSTRAINT FK_b2ab3dee_d336_46a0_8614_596c825d2232 FOREIGN KEY ([TRANSRECID]) REFERENCES [dbo].[CustTrans_to_AML]([RECID]);