table 'agosto 2024'
	isHidden
	lineageTag: eb04f98d-25d1-4f6c-bf53-9c53d11d7d2a

	column DESCRIPCION_DIVISION
		dataType: string
		isHidden
		lineageTag: 83fabdcc-7d2c-4556-8708-bef71cb82aae
		summarizeBy: none
		sourceColumn: DESCRIPCION_DIVISION

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DESCRIPCION_OFICINA
		dataType: string
		isHidden
		lineageTag: 53a7516c-a705-4ef4-a54c-7adcaf7aa911
		summarizeBy: none
		sourceColumn: DESCRIPCION_OFICINA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AGRUPACION
		dataType: string
		isHidden
		lineageTag: b3cc2316-a8a8-48a1-a529-b300186f2e23
		summarizeBy: none
		sourceColumn: AGRUPACION

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CLAVE_ESPEJO
		dataType: string
		isHidden
		lineageTag: 0e2df453-6920-4143-b66d-09666bd1171e
		summarizeBy: none
		sourceColumn: CLAVE_ESPEJO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CLAVE_AGENTE
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f7cdca1f-2e15-4cd0-8a0e-391e452937cb
		summarizeBy: none
		sourceColumn: CLAVE_AGENTE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NOMBRE_AGENTE
		dataType: string
		isHidden
		lineageTag: 9e66a474-c7f1-4b13-8fc1-f145b5405b81
		summarizeBy: none
		sourceColumn: NOMBRE_AGENTE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'PRIMA COBRADA'
		dataType: double
		isHidden
		lineageTag: bc88166e-ddfd-4e81-bd07-d7e527457680
		summarizeBy: sum
		sourceColumn: PRIMA COBRADA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'PRIMA NETA'
		dataType: double
		isHidden
		lineageTag: d6ca5037-39a4-4aca-8481-ed7041474f4f
		summarizeBy: sum
		sourceColumn: PRIMA NETA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CNS
		dataType: double
		isHidden
		lineageTag: 5da9e5eb-f926-45f7-82f2-693ec24a7377
		summarizeBy: sum
		sourceColumn: CNS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'PRIMA DEVENGADA'
		dataType: double
		isHidden
		lineageTag: a12245dc-695d-4c6b-87a4-43debed6ad34
		summarizeBy: sum
		sourceColumn: PRIMA DEVENGADA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SINIESTRALIDAD
		dataType: double
		isHidden
		lineageTag: 32b75565-2d29-4071-9f94-fd3c893c5374
		summarizeBy: sum
		sourceColumn: SINIESTRALIDAD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'PRIMA PROMEDIO HISTORICA'
		dataType: double
		isHidden
		lineageTag: cdba7646-3eb6-42f5-a599-c5115bfddff1
		summarizeBy: sum
		sourceColumn: PRIMA PROMEDIO HISTORICA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '% DESCUENTO'
		dataType: double
		isHidden
		lineageTag: 07f6bb14-564c-48ef-9b64-de72da916057
		summarizeBy: sum
		sourceColumn: % DESCUENTO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FRECUENCIA
		dataType: double
		isHidden
		lineageTag: f3e70b30-03b2-4669-b288-332dfdb57a49
		summarizeBy: sum
		sourceColumn: FRECUENCIA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'COSTO PROMEDIO DE SINIESTRO'
		dataType: string
		isHidden
		lineageTag: 6da9cef3-248e-4cea-99ae-6c648ae8bb6a
		summarizeBy: none
		sourceColumn: COSTO PROMEDIO DE SINIESTRO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EXPUESTO
		dataType: double
		isHidden
		lineageTag: 0aad633d-5b4b-4aa8-994a-c9edee4abd9e
		summarizeBy: sum
		sourceColumn: EXPUESTO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'NUMERO DE SINIESTROS'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 582f1981-6907-4ab9-85aa-82be6418214b
		summarizeBy: sum
		sourceColumn: NUMERO DE SINIESTROS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 6f49570a-ef28-4e6e-a098-8b0a99e1e16c
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: 472d0b46-e2b0-4604-a2d1-03397d68126c
			defaultHierarchy: LocalDateTable_0b96579e-0c6b-4de1-a3da-fe080945c00a.'Jerarquía de fechas'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Siniestralidad '
		dataType: string
		isHidden
		lineageTag: 52b1f8b8-40d5-4282-8e1b-6f1acf498aee
		summarizeBy: none
		sourceColumn: "Siniestralidad "

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'agosto 2024' = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\GabrielArmandoChávez\GONZALEZ CORTINA GLENDER Y CIA\ZAP BI - Documentos compartidos\02 OPORTUNIDADES\Oportunidades 2024\Ana Seguros\data\PwNMRv agosto 2024.xlsx"), null, true),
				    #"MyWorkSheet-1_Sheet" = Origen{[Item="MyWorkSheet-1",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"MyWorkSheet-1_Sheet", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"DESCRIPCION_DIVISION", type text}, {"DESCRIPCION_OFICINA", type text}, {"AGRUPACION", Int64.Type}, {"CLAVE_ESPEJO", type text}, {"CLAVE_AGENTE", Int64.Type}, {"NOMBRE_AGENTE", type text}, {"PRIMA COBRADA", type number}, {"PRIMA NETA", type number}, {"CNS", type number}, {"PRIMA DEVENGADA", type number}, {"SINIESTRALIDAD", type number}, {"PRIMA PROMEDIO HISTORICA", type number}, {"% DESCUENTO", type number}, {"FRECUENCIA", type number}, {"COSTO PROMEDIO DE SINIESTRO", type any}, {"EXPUESTO", type number}, {"NUMERO DE SINIESTROS", Int64.Type}}),
				    #"Filas superiores quitadas" = Table.Skip(#"Tipo cambiado",1),
				    #"Personalizada agregada" = Table.AddColumn(#"Filas superiores quitadas", "Fecha", each "agosto 2024"),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Personalizada agregada",{{"Fecha", type date}}),
				    #"Personalizada agregada1" = Table.AddColumn(#"Tipo cambiado1", "Siniestralidad ", each [CNS]/[PRIMA DEVENGADA]),
				    #"Errores reemplazados" = Table.ReplaceErrorValues(#"Personalizada agregada1", {{"PRIMA PROMEDIO HISTORICA", null}}),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Errores reemplazados",{{"AGRUPACION", type text}})
				in
				    #"Tipo cambiado2"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

