table 'diciembre 2023'
	isHidden
	lineageTag: e4e65874-4eaa-437f-8809-203bdfb35cb8

	column DESCRIPCION_DIVISION
		dataType: string
		isHidden
		lineageTag: 18831419-02c1-4582-b894-a202063e643d
		summarizeBy: none
		sourceColumn: DESCRIPCION_DIVISION

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DESCRIPCION_OFICINA
		dataType: string
		isHidden
		lineageTag: 8debeb4f-05ad-489d-84eb-ec0d98ac9e6a
		summarizeBy: none
		sourceColumn: DESCRIPCION_OFICINA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AGRUPACION
		dataType: string
		isHidden
		lineageTag: 426f53a3-ee32-4a5a-bafe-fb4cbb08fb39
		summarizeBy: none
		sourceColumn: AGRUPACION

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CLAVE_ESPEJO
		dataType: string
		isHidden
		lineageTag: f5b06217-4f28-4664-8e3f-35f894e87dae
		summarizeBy: none
		sourceColumn: CLAVE_ESPEJO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CLAVE_AGENTE
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 9775f46b-73fb-4c0a-a6b6-eb8fd06b6aee
		summarizeBy: none
		sourceColumn: CLAVE_AGENTE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NOMBRE_AGENTE
		dataType: string
		isHidden
		lineageTag: de1350cf-4b4d-41e3-97af-8bd86138052b
		summarizeBy: none
		sourceColumn: NOMBRE_AGENTE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'PRIMA COBRADA'
		dataType: double
		isHidden
		lineageTag: 0072fa28-0123-49a7-b8ad-0010240a86cc
		summarizeBy: sum
		sourceColumn: PRIMA COBRADA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'PRIMA NETA'
		dataType: double
		isHidden
		lineageTag: 461601d2-6eb8-44b0-b708-6f0e00decb1b
		summarizeBy: sum
		sourceColumn: PRIMA NETA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CNS
		dataType: double
		isHidden
		lineageTag: 6b1f589f-e774-4703-ab4b-aa8222af714e
		summarizeBy: sum
		sourceColumn: CNS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'PRIMA DEVENGADA'
		dataType: double
		isHidden
		lineageTag: 89d57f23-b8b7-468f-a445-a9d9459d9c57
		summarizeBy: sum
		sourceColumn: PRIMA DEVENGADA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SINIESTRALIDAD
		dataType: double
		isHidden
		lineageTag: 5c43d978-4259-43a2-80c3-45a872001a50
		summarizeBy: sum
		sourceColumn: SINIESTRALIDAD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'PRIMA PROMEDIO HISTORICA'
		dataType: double
		isHidden
		lineageTag: afd2d017-672e-4507-be76-1287c0aa0c00
		summarizeBy: sum
		sourceColumn: PRIMA PROMEDIO HISTORICA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '% DESCUENTO'
		dataType: double
		isHidden
		lineageTag: b71846f5-638a-4e32-be49-521d822314ce
		summarizeBy: sum
		sourceColumn: % DESCUENTO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FRECUENCIA
		dataType: double
		isHidden
		lineageTag: 480ea8a0-1bc9-48f0-a9e6-50c3d2adfd41
		summarizeBy: sum
		sourceColumn: FRECUENCIA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'COSTO PROMEDIO DE SINIESTRO'
		dataType: string
		isHidden
		lineageTag: be473b9d-b374-4205-a815-f20246694550
		summarizeBy: none
		sourceColumn: COSTO PROMEDIO DE SINIESTRO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EXPUESTO
		dataType: double
		isHidden
		lineageTag: 28cf7f17-cb66-4960-baeb-fa603ac42480
		summarizeBy: sum
		sourceColumn: EXPUESTO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'NUMERO DE SINIESTROS'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 7ccd6d2f-3007-4f28-b17a-cc77676607f0
		summarizeBy: sum
		sourceColumn: NUMERO DE SINIESTROS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: d7270d03-d5b5-4b53-b97f-d73e48ad1f97
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: 4dcd4497-eb92-4a8b-9250-fb269269bf62
			defaultHierarchy: LocalDateTable_5495467a-78e9-4f6e-b46f-74b41f016d12.'Jerarquía de fechas'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Siniestralidad '
		dataType: string
		isHidden
		lineageTag: cd53cdfd-e4d4-4008-ae0f-27b2bbfe9497
		summarizeBy: none
		sourceColumn: "Siniestralidad "

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'diciembre 2023' = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\GabrielArmandoChávez\GONZALEZ CORTINA GLENDER Y CIA\ZAP BI - Documentos compartidos\02 OPORTUNIDADES\Oportunidades 2024\Ana Seguros\data\PwNMRv diciembre 2023.xlsx"), null, true),
				    #"MyWorkSheet-1_Sheet" = Origen{[Item="MyWorkSheet-1",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"MyWorkSheet-1_Sheet", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"DESCRIPCION_DIVISION", type text}, {"DESCRIPCION_OFICINA", type text}, {"AGRUPACION", Int64.Type}, {"CLAVE_ESPEJO", type text}, {"CLAVE_AGENTE", Int64.Type}, {"NOMBRE_AGENTE", type text}, {"PRIMA COBRADA", type number}, {"PRIMA NETA", type number}, {"CNS", type number}, {"PRIMA DEVENGADA", type number}, {"SINIESTRALIDAD", type number}, {"PRIMA PROMEDIO HISTORICA", type number}, {"% DESCUENTO", type number}, {"FRECUENCIA", type number}, {"COSTO PROMEDIO DE SINIESTRO", type any}, {"EXPUESTO", type number}, {"NUMERO DE SINIESTROS", Int64.Type}}),
				    #"Filas superiores quitadas" = Table.Skip(#"Tipo cambiado",1),
				    #"Personalizada agregada" = Table.AddColumn(#"Filas superiores quitadas", "Fecha", each "diciembre 2023"),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Personalizada agregada",{{"Fecha", type date}}),
				    #"Personalizada agregada1" = Table.AddColumn(#"Tipo cambiado1", "Siniestralidad ", each [CNS]/[PRIMA DEVENGADA]),
				    #"Errores reemplazados" = Table.ReplaceErrorValues(#"Personalizada agregada1", {{"SINIESTRALIDAD", null}}),
				    #"Errores reemplazados1" = Table.ReplaceErrorValues(#"Errores reemplazados", {{"PRIMA PROMEDIO HISTORICA", null}}),
				    #"Errores reemplazados2" = Table.ReplaceErrorValues(#"Errores reemplazados1", {{"FRECUENCIA", null}}),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Errores reemplazados2",{{"AGRUPACION", type text}})
				in
				    #"Tipo cambiado2"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

