table 'enero 2023'
	isHidden
	lineageTag: c6fd8291-ee13-40d2-bf08-2191c3262004

	column DESCRIPCION_DIVISION
		dataType: string
		isHidden
		lineageTag: a3df078a-a1e8-452d-8e2a-3ab8a855de82
		summarizeBy: none
		sourceColumn: DESCRIPCION_DIVISION

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DESCRIPCION_OFICINA
		dataType: string
		isHidden
		lineageTag: cf726261-1a88-4d0d-9e88-7011cf8a1104
		summarizeBy: none
		sourceColumn: DESCRIPCION_OFICINA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AGRUPACION
		dataType: string
		isHidden
		lineageTag: 09a6deb6-c644-4276-8c95-010ca0fd9936
		summarizeBy: none
		sourceColumn: AGRUPACION

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CLAVE_ESPEJO
		dataType: string
		isHidden
		lineageTag: 2a0ab6fb-40fc-45a7-8dd8-1b951f1e2bfd
		summarizeBy: none
		sourceColumn: CLAVE_ESPEJO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CLAVE_AGENTE
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1f055be3-c7c6-4e44-9a90-7f641993951d
		summarizeBy: none
		sourceColumn: CLAVE_AGENTE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NOMBRE_AGENTE
		dataType: string
		isHidden
		lineageTag: 3e55afbc-8da1-4ee5-9dff-cbd0d5c9a92e
		summarizeBy: none
		sourceColumn: NOMBRE_AGENTE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'PRIMA COBRADA'
		dataType: double
		isHidden
		lineageTag: a031e67a-a26f-48c0-89f1-339f8ca3f51d
		summarizeBy: sum
		sourceColumn: PRIMA COBRADA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'PRIMA NETA'
		dataType: double
		isHidden
		lineageTag: bc3bc552-dbf5-49bf-b8f9-c66126289a2e
		summarizeBy: sum
		sourceColumn: PRIMA NETA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CNS
		dataType: double
		isHidden
		lineageTag: 95fe0657-5cfd-4e64-be3b-ee241bcfba15
		summarizeBy: sum
		sourceColumn: CNS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'PRIMA DEVENGADA'
		dataType: double
		isHidden
		lineageTag: e2196b47-1008-48bc-af28-6902e576f912
		summarizeBy: sum
		sourceColumn: PRIMA DEVENGADA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SINIESTRALIDAD
		dataType: double
		isHidden
		lineageTag: e5e2e86e-f2c8-4d1d-aa22-1f2d5e9206f1
		summarizeBy: sum
		sourceColumn: SINIESTRALIDAD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'PRIMA PROMEDIO HISTORICA'
		dataType: double
		isHidden
		lineageTag: c13d1467-37dc-439d-9591-2ef65025886a
		summarizeBy: sum
		sourceColumn: PRIMA PROMEDIO HISTORICA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '% DESCUENTO'
		dataType: double
		isHidden
		lineageTag: 13c3a3f1-be61-41f8-8281-6a7e2de149e1
		summarizeBy: sum
		sourceColumn: % DESCUENTO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FRECUENCIA
		dataType: double
		isHidden
		lineageTag: 0cea0518-0fd7-4939-8804-0046986c4630
		summarizeBy: sum
		sourceColumn: FRECUENCIA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'COSTO PROMEDIO DE SINIESTRO'
		dataType: string
		isHidden
		lineageTag: 2bcfc5a8-5906-41ed-a2f1-896e075f1120
		summarizeBy: none
		sourceColumn: COSTO PROMEDIO DE SINIESTRO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EXPUESTO
		dataType: double
		isHidden
		lineageTag: 2962d296-19c6-4bd4-8ee8-745b7a134e2d
		summarizeBy: sum
		sourceColumn: EXPUESTO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'NUMERO DE SINIESTROS'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b158813f-d9b6-4eff-83cc-58198718ad79
		summarizeBy: sum
		sourceColumn: NUMERO DE SINIESTROS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 6a1f1556-8d98-4800-a72c-f26b80e9c156
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: 8de3d1be-d36b-46e3-9262-c0e72aec0c3f
			defaultHierarchy: LocalDateTable_0e28a47a-3bad-48b9-bd28-9aaab5ef559d.'Jerarquía de fechas'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Siniestralidad '
		dataType: string
		isHidden
		lineageTag: 2c6444cf-9f5c-43a2-83c9-bedc52957900
		summarizeBy: none
		sourceColumn: "Siniestralidad "

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'enero 2023' = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\GabrielArmandoChávez\GONZALEZ CORTINA GLENDER Y CIA\ZAP BI - Documentos compartidos\02 OPORTUNIDADES\Oportunidades 2024\Ana Seguros\data\PwNMRv enero 2023.xlsx"), null, true),
				    #"MyWorkSheet-1_Sheet" = Origen{[Item="MyWorkSheet-1",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"MyWorkSheet-1_Sheet", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"DESCRIPCION_DIVISION", type text}, {"DESCRIPCION_OFICINA", type text}, {"AGRUPACION", Int64.Type}, {"CLAVE_ESPEJO", type text}, {"CLAVE_AGENTE", Int64.Type}, {"NOMBRE_AGENTE", type text}, {"PRIMA COBRADA", type number}, {"PRIMA NETA", type number}, {"CNS", type number}, {"PRIMA DEVENGADA", type number}, {"SINIESTRALIDAD", type number}, {"PRIMA PROMEDIO HISTORICA", type number}, {"% DESCUENTO", type number}, {"FRECUENCIA", type number}, {"COSTO PROMEDIO DE SINIESTRO", type any}, {"EXPUESTO", type number}, {"NUMERO DE SINIESTROS", Int64.Type}}),
				    #"Filas superiores quitadas" = Table.Skip(#"Tipo cambiado",1),
				    #"Personalizada agregada" = Table.AddColumn(#"Filas superiores quitadas", "Fecha", each "enero 2023"),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Personalizada agregada",{{"Fecha", type date}}),
				    #"Personalizada agregada1" = Table.AddColumn(#"Tipo cambiado1", "Siniestralidad ", each [CNS]/[PRIMA DEVENGADA]),
				    #"Errores reemplazados" = Table.ReplaceErrorValues(#"Personalizada agregada1", {{"SINIESTRALIDAD", null}}),
				    #"Errores reemplazados1" = Table.ReplaceErrorValues(#"Errores reemplazados", {{"PRIMA PROMEDIO HISTORICA", null}}),
				    #"Errores reemplazados2" = Table.ReplaceErrorValues(#"Errores reemplazados1", {{"FRECUENCIA", null}}),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Errores reemplazados2",{{"AGRUPACION", type text}})
				in
				    #"Tipo cambiado2"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

