table 'febrero 2023'
	isHidden
	lineageTag: 4e021019-8d2a-4aad-b106-9b90c60eebf8

	column DESCRIPCION_DIVISION
		dataType: string
		isHidden
		lineageTag: 899e21b0-586c-4d80-8958-c98df55aa9b3
		summarizeBy: none
		sourceColumn: DESCRIPCION_DIVISION

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DESCRIPCION_OFICINA
		dataType: string
		isHidden
		lineageTag: 7f97ecf6-462a-432e-9cfa-f4140ae02b63
		summarizeBy: none
		sourceColumn: DESCRIPCION_OFICINA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AGRUPACION
		dataType: string
		isHidden
		lineageTag: ed0dae5c-203e-4249-b006-7f90fa8021ba
		summarizeBy: none
		sourceColumn: AGRUPACION

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CLAVE_ESPEJO
		dataType: string
		isHidden
		lineageTag: 43ac9e35-2270-4860-a77c-0967a7348306
		summarizeBy: none
		sourceColumn: CLAVE_ESPEJO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CLAVE_AGENTE
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 532870cd-7e2b-4067-9093-c60fb54d18fd
		summarizeBy: none
		sourceColumn: CLAVE_AGENTE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NOMBRE_AGENTE
		dataType: string
		isHidden
		lineageTag: 4f89fcfb-7a04-492f-883f-b9ed8ec0447b
		summarizeBy: none
		sourceColumn: NOMBRE_AGENTE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'PRIMA COBRADA'
		dataType: double
		isHidden
		lineageTag: ae8e36c8-68c6-483b-b544-d3daa2375e48
		summarizeBy: sum
		sourceColumn: PRIMA COBRADA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'PRIMA NETA'
		dataType: double
		isHidden
		lineageTag: d096720d-959a-4ff3-8180-cf8aaa834b72
		summarizeBy: sum
		sourceColumn: PRIMA NETA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CNS
		dataType: double
		isHidden
		lineageTag: fee6cc99-6e2b-4921-9ff7-364cbb08aff2
		summarizeBy: sum
		sourceColumn: CNS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'PRIMA DEVENGADA'
		dataType: double
		isHidden
		lineageTag: 4c1b9acb-d71b-4ce0-a840-376d0bb3a830
		summarizeBy: sum
		sourceColumn: PRIMA DEVENGADA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SINIESTRALIDAD
		dataType: double
		isHidden
		lineageTag: 59d6214e-12c6-4698-ad88-7323a4dc55c7
		summarizeBy: sum
		sourceColumn: SINIESTRALIDAD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'PRIMA PROMEDIO HISTORICA'
		dataType: double
		isHidden
		lineageTag: 352a698c-43b4-4f2f-a1c5-c37a97bb3f08
		summarizeBy: sum
		sourceColumn: PRIMA PROMEDIO HISTORICA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '% DESCUENTO'
		dataType: double
		isHidden
		lineageTag: 87574831-92d7-4df1-aa90-23bd78867bdd
		summarizeBy: sum
		sourceColumn: % DESCUENTO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FRECUENCIA
		dataType: double
		isHidden
		lineageTag: 872be36b-7c52-4d56-982e-02c6d9e35ffe
		summarizeBy: sum
		sourceColumn: FRECUENCIA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'COSTO PROMEDIO DE SINIESTRO'
		dataType: string
		isHidden
		lineageTag: 973b26ab-4875-4ef3-b4d0-4b8be80799a4
		summarizeBy: none
		sourceColumn: COSTO PROMEDIO DE SINIESTRO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EXPUESTO
		dataType: double
		isHidden
		lineageTag: 5ddcdfe6-57af-400e-96ba-4e9c7f8e35c4
		summarizeBy: sum
		sourceColumn: EXPUESTO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'NUMERO DE SINIESTROS'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4e2d8e00-4717-4da3-9f81-750d45c87093
		summarizeBy: sum
		sourceColumn: NUMERO DE SINIESTROS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: fe952355-f668-4e2d-9610-abee189da2b7
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: 89115f89-83f9-4699-a923-19162033f9f8
			defaultHierarchy: LocalDateTable_22142b2e-3a28-42fc-96fd-7a421d9a778f.'Jerarquía de fechas'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Siniestralidad '
		dataType: string
		isHidden
		lineageTag: 0a0636a6-49fb-4b66-ac4d-d8fde0230b7e
		summarizeBy: none
		sourceColumn: "Siniestralidad "

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'febrero 2023' = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\GabrielArmandoChávez\GONZALEZ CORTINA GLENDER Y CIA\ZAP BI - Documentos compartidos\02 OPORTUNIDADES\Oportunidades 2024\Ana Seguros\data\PwNMRv febrero 2023.xlsx"), null, true),
				    #"MyWorkSheet-1_Sheet" = Origen{[Item="MyWorkSheet-1",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"MyWorkSheet-1_Sheet", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"DESCRIPCION_DIVISION", type text}, {"DESCRIPCION_OFICINA", type text}, {"AGRUPACION", Int64.Type}, {"CLAVE_ESPEJO", type text}, {"CLAVE_AGENTE", Int64.Type}, {"NOMBRE_AGENTE", type text}, {"PRIMA COBRADA", type number}, {"PRIMA NETA", type number}, {"CNS", type number}, {"PRIMA DEVENGADA", type number}, {"SINIESTRALIDAD", type number}, {"PRIMA PROMEDIO HISTORICA", type number}, {"% DESCUENTO", type number}, {"FRECUENCIA", type number}, {"COSTO PROMEDIO DE SINIESTRO", type any}, {"EXPUESTO", type number}, {"NUMERO DE SINIESTROS", Int64.Type}}),
				    #"Filas superiores quitadas" = Table.Skip(#"Tipo cambiado",1),
				    #"Personalizada agregada" = Table.AddColumn(#"Filas superiores quitadas", "Fecha", each "febrero 2023"),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Personalizada agregada",{{"Fecha", type date}}),
				    #"Personalizada agregada1" = Table.AddColumn(#"Tipo cambiado1", "Siniestralidad ", each [CNS]/[PRIMA DEVENGADA]),
				    #"Errores reemplazados" = Table.ReplaceErrorValues(#"Personalizada agregada1", {{"SINIESTRALIDAD", null}}),
				    #"Errores reemplazados1" = Table.ReplaceErrorValues(#"Errores reemplazados", {{"PRIMA PROMEDIO HISTORICA", null}}),
				    #"Errores reemplazados2" = Table.ReplaceErrorValues(#"Errores reemplazados1", {{"FRECUENCIA", null}}),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Errores reemplazados2",{{"AGRUPACION", type text}})
				in
				    #"Tipo cambiado2"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

