table Categoría
	lineageTag: 8df960b2-5731-4151-af9b-d11f737cc7e2

	column id
		dataType: int64
		formatString: 0
		lineageTag: 9a0e8f49-2e6c-4cb5-bba9-be36fb313e27
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column Categoría
		dataType: string
		lineageTag: 264b98a5-27a2-477c-9a91-d01a5ed46e8a
		summarizeBy: none
		sourceColumn: Categoría

		annotation SummarizationSetBy = Automatic

	partition Categoría = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\GabrielArmandoChávez\GONZALEZ CORTINA GLENDER Y CIA\ZAP BI - Documentos compartidos\02 OPORTUNIDADES\Oportunidades 2024\IPN\PoC\catalogos.xlsx"), null, true),
				    Categoría_Sheet = Origen{[Item="Categoría",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Categoría_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id", Int64.Type}, {"Categoría", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Exception

