table PROCESOS
	lineageTag: 6b09afe9-3ca8-4faa-8ae3-32426871dd82

	column PROCESOS
		dataType: string
		lineageTag: 190da2ba-3318-4808-8bdf-5e0c1685a66e
		summarizeBy: none
		sourceColumn: PROCESOS

		annotation SummarizationSetBy = Automatic

	column ORDEN
		dataType: int64
		formatString: 0
		lineageTag: 5cfeb9a3-203d-4249-bf8d-0ec6ac14f20d
		summarizeBy: none
		sourceColumn: ORDEN

		annotation SummarizationSetBy = Automatic

	column ID_PROCESOS
		dataType: string
		lineageTag: 2e718481-b369-4a56-a4fb-e121e0a902ec
		summarizeBy: none
		sourceColumn: ID_PROCESOS

		annotation SummarizationSetBy = Automatic

	partition PROCESOS = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("Zc9LDsIgEIDhqxDWNSl9dznSSUQRGkqJsWHhmTySFxNG000XbPh+GNg2jg/vQEr1eRtecJFXKXgsNu6d8muyP1VEFdG86oBOPWGybEYv7Q2TNlS0J1F2h0qCO1sD3i4pqilsKJKgpTL7lJaoJ7qDwatlE6bTmgUVIGFHwXAc8LJJetKR9KImB36/ecgkfl9DE2DJTx5ps+YxfgE=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [PROCESOS = _t, ORDEN = _t, ID_PROCESOS = _t]),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(Origen,{{"ORDEN", Int64.Type}}),
				    #"Filas ordenadas" = Table.Sort(#"Tipo cambiado1",{{"ORDEN", Order.Ascending}})
				in
				    #"Filas ordenadas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

